fix(storage): resolve crashes when calling nested StorageModule
Per the ticket, the Angular compiler wasn's able to resolve all
dependencies because they were imported through barrels.

> ERROR: Can't resolve all parameters for ɵg in $PROJECT_PATH:
> (?, [object Object], [object Object], [object Object]).

The above error maps to the constructor for StorageEffects:

```typescript
constructor(
  @Inject(STORAGE_CONFIG) private readonly config: ModuleConfig,
  private readonly actions$: Actions,
  private readonly storage: Storage,
  private readonly store$: Store<any>
) {}
```

The file originally imported STORAGE_CONFIG from a barrel:

```typescript
import { STORAGE_CONFIG } from '../providers/config.provider';
```

Importing directly from the file fixes this:

```typescript
import { STORAGE_CONFIG } from '../providers/config.provider';
```

1. Move meta-reducer provider to module to sidestep compile errors.
2. Change paths to not be from barrel, but directly from the source.

Closes: d4h/decisions-project#3771